services:
  dtp01:
    image: $IMAGE_DTP_DOCKER_REPO:$IMAGE_DTP_DOCKER_TAG
    container_name: dtp01
    environment:
      ROOT_DATA_FOLDER: /var/datareon/platformRoot
      STORAGE_FOLDER: /var/datareon/platformStorage
      LOG_KEY: /var/log/datareon
      NODE_PORT_KEY: 8888
      CONTROL_SERVER_PORT_KEY: 8887
    volumes:
      - datareon:/var/datareon
      - datareon-log:/var/log/datareon
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10.129.7.5:5199:5199"
      - "10.129.7.5:5557:5557"
      - "10.129.7.5:7200:7200"
      - "10.129.7.5:7201:7201"
      - "10.129.7.5:7202:7202"
      - "10.129.7.5:7203:7203"
      - "10.129.7.5:7205:7205"
      - "10.129.7.5:7206:7206"
      - "10.129.7.5:7290:7290"
      - "10.129.7.5:7295:7295"
      - "10.129.7.5:7298:7298"
      - "10.129.7.5:7928:7928"
      - "10.129.7.5:8001:8001"
      - "10.129.7.5:8060-8079:8060-8079"
      - "10.129.7.5:8888:8888"
      - "10.129.7.5:8887:8887"
      - "10.129.7.5:9090:9090"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 16g
    restart: unless-stopped
    networks:
      - dtp01

volumes:
  datareon:
    driver: local
    name: dtp01-datareon
  datareon-log:
    driver: local
    name: dtp01-datareon-log

networks:
  dtp01:
    name: dtp01-network